In [1]:
import subprocess

import pandas as pd

In [2]:
TARGET_COLUMNS = [ 
    'hospital_id',
    #'row_id',
    'line_type',
    'description',
    'rev_code',
    'local_code',
    'code',
    'ms_drg',
    'apr_drg',
    'eapg',
    'hcpcs_cpt',
    'modifiers',
    'alt_hcpcs_cpt',
    'thru',
    'apc',
    'icd',
    'ndc',
    'drug_hcpcs_multiplier',
    'drug_quantity',
    'drug_unit_of_measurement',
    'drug_type_of_measurement',
    'billing_class',
    'setting',
    'payer_category',
    'payer_name',
    'plan_name',
    'standard_charge',
    'standard_charge_percent',
    'contracting_method',
    'additional_generic_notes',
    'additional_payer_specific_notes'
]

In [3]:
# https://www.albanymed.org/patients-visitors/billing-insurance/hospital-pricing-transparency/
ccn = "330013"
url = "https://www.albanymed.org/wp-content/uploads/attachements/141338307_AlbanyMedicalCenter_standardcharges.csv"
filename = url.split("/")[-1].replace("%20", " ")
ein = filename.split("_")[0]
ein = ein[:2] + "-" + ein[2:]
ein

'14-1338307'

In [4]:
import subprocess
subprocess.run(["wget", "--no-clobber", url, "-O", filename])

File ‘141338307_AlbanyMedicalCenter_standardcharges.csv’ already there; not retrieving.

CompletedProcess(args=['wget', '--no-clobber', 'https://www.albanymed.org/wp-content/uploads/attachements/141338307_AlbanyMedicalCenter_standardcharges.csv', '-O', '141338307_AlbanyMedicalCenter_standardcharges.csv'], returncode=1)

In [5]:
df_in = pd.read_csv(filename, encoding='latin-1', skiprows=[0,1], low_memory=False)
df_in

,Charge Code,Description,CPT® Code,Revenue Code,Gross Charge/Unit,Additonal Comment,Cash Price,MinRate,MaxRate,Beech Street,Excellus-RMSCO,HRGi,PHCS,UHC Commercial IP,UHC Commercial OP
0,0656D3NPX,RMBD PRIVATE,NaN,0111,2890.00,NaN,2312.00,2167.50,2456.50,2456.50,2456.5,2456.5,2456.5,2167.5,2312.0
1,0656D3NPXALC,RMBD PRIVATE ALC,NaN,0111,2890.00,NaN,2312.00,2167.50,2456.50,2456.50,2456.5,2456.5,2456.5,2167.5,2312.0
2,0656PX,RMBD PRIVATE,NaN,0111,2890.00,NaN,2312.00,2167.50,2456.50,2456.50,2456.5,2456.5,2456.5,2167.5,2312.0
3,0656PXALC,RMBD PRIVATE ALC,NaN,0111,2890.00,NaN,2312.00,2167.50,2456.50,2456.50,2456.5,2456.5,2456.5,2167.5,2312.0
4,8535PX,RMBD PRIVATE,NaN,0111,2890.00,NaN,2312.00,2167.50,2456.50,2456.50,2456.5,2456.5,2456.5,2167.5,2312.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
387081,United The Empire Plan,CPT,97162,Pt eval mod complex 30 min,NaN,Straight Discount,80.00%,80.00%,80.00%,OP,NaN,NaN,NaN,NaN,NaN
387082,United The Empire Plan,CPT,97163,Pt eval high complex 45 min,NaN,Straight Discount,80.00%,80.00%,80.00%,OP,NaN,NaN,NaN,NaN,NaN
387083,United The Empire Plan,CPT,97165,Ot eval low complex 30 min,NaN,Straight Discount,80.00%,80.00%,80.00%,OP,NaN,NaN,NaN,NaN,NaN
387084,United The Empire Plan,CPT,97166,Ot eval mod complex 45 min,NaN,Straight Discount,80.00%,80.00%,80.00%,OP,NaN,NaN,NaN,NaN,NaN
387085,United The Empire Plan,CPT,U0004,Cov-19 test non-cdc hgh thru,NaN,Straight Discount,80.00%,80.00%,80.00%,OP,NaN,NaN,NaN,NaN,NaN

In [6]:
delim_idx = df_in[df_in['Charge Code'] == 'Table 2: Payer Negotiated Rates'].index.to_list()[0]
delim_idx

63056

In [7]:
df_in1 = pd.DataFrame(df_in.head(delim_idx))
df_in1

,Charge Code,Description,CPT® Code,Revenue Code,Gross Charge/Unit,Additonal Comment,Cash Price,MinRate,MaxRate,Beech Street,Excellus-RMSCO,HRGi,PHCS,UHC Commercial IP,UHC Commercial OP
0,0656D3NPX,RMBD PRIVATE,NaN,0111,2890.00,NaN,2312.00,2167.50,2456.50,2456.50,2456.50,2456.50,2456.50,2167.50,2312.00
1,0656D3NPXALC,RMBD PRIVATE ALC,NaN,0111,2890.00,NaN,2312.00,2167.50,2456.50,2456.50,2456.50,2456.50,2456.50,2167.50,2312.00
2,0656PX,RMBD PRIVATE,NaN,0111,2890.00,NaN,2312.00,2167.50,2456.50,2456.50,2456.50,2456.50,2456.50,2167.50,2312.00
3,0656PXALC,RMBD PRIVATE ALC,NaN,0111,2890.00,NaN,2312.00,2167.50,2456.50,2456.50,2456.50,2456.50,2456.50,2167.50,2312.00
4,8535PX,RMBD PRIVATE,NaN,0111,2890.00,NaN,2312.00,2167.50,2456.50,2456.50,2456.50,2456.50,2456.50,2167.50,2312.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63051,72099182,METHYLDOPATE INJ 250MG 72099182,J0210,0999,93.15,NaN,74.52,69.86,79.18,79.18,79.18,79.18,79.18,69.86,74.52
63052,72046836,PHENTOLAMINE INJ 5MG 72046836,J2760,0999,932.88,NaN,746.30,699.66,792.95,792.95,792.95,792.95,792.95,699.66,746.30
63053,72078908,ROPIVACAINE 1MG 400MG 72078908,J2795,0999,94.18,NaN,75.34,70.64,80.05,80.05,80.05,80.05,80.05,70.64,75.34
63054,72078758,BILVALIRUDIN INJ 1MG 20MG 72078758,J0583,0999,94.50,NaN,75.60,70.88,80.33,80.33,80.33,80.33,80.33,70.88,75.60
63055,72000048,HEPATITIS B VAC 1ML 90731 72000048,90746,0999,99.80,NaN,79.84,74.85,84.83,84.83,84.83,84.83,84.83,74.85,79.84

In [8]:
set(df_in1['Additonal Comment'].to_list())

{'* "Gross Charge/Unit" amount varies based on the acquisition cost and vendor utilized.\xa0 The gross charge amount represents the average charge.',
 '** "Gross Charge/Unit" amount varies based on tiered interval time charges.\xa0 The Gross Charge/Unit amount represents the average charge with a minimum of 15 minutes.\xa0 ',
 nan}

In [9]:
df_mid1 = pd.DataFrame(df_in1)
df_mid1 = df_mid1.rename(columns={
    'Charge Code': 'local_code',
    'Description': 'description',
    'CPT® Code': 'hcpcs_cpt',
    'Revenue Code': 'rev_code',
    'Additonal Comment': 'additional_generic_notes'
})

# https://stackoverflow.com/a/67894930
column_to_move = df_mid1.pop("additional_generic_notes")
df_mid1.insert(0, "additional_generic_notes", column_to_move)

df_mid1

,additional_generic_notes,local_code,description,hcpcs_cpt,rev_code,Gross Charge/Unit,Cash Price,MinRate,MaxRate,Beech Street,Excellus-RMSCO,HRGi,PHCS,UHC Commercial IP,UHC Commercial OP
0,NaN,0656D3NPX,RMBD PRIVATE,NaN,0111,2890.00,2312.00,2167.50,2456.50,2456.50,2456.50,2456.50,2456.50,2167.50,2312.00
1,NaN,0656D3NPXALC,RMBD PRIVATE ALC,NaN,0111,2890.00,2312.00,2167.50,2456.50,2456.50,2456.50,2456.50,2456.50,2167.50,2312.00
2,NaN,0656PX,RMBD PRIVATE,NaN,0111,2890.00,2312.00,2167.50,2456.50,2456.50,2456.50,2456.50,2456.50,2167.50,2312.00
3,NaN,0656PXALC,RMBD PRIVATE ALC,NaN,0111,2890.00,2312.00,2167.50,2456.50,2456.50,2456.50,2456.50,2456.50,2167.50,2312.00
4,NaN,8535PX,RMBD PRIVATE,NaN,0111,2890.00,2312.00,2167.50,2456.50,2456.50,2456.50,2456.50,2456.50,2167.50,2312.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63051,NaN,72099182,METHYLDOPATE INJ 250MG 72099182,J0210,0999,93.15,74.52,69.86,79.18,79.18,79.18,79.18,79.18,69.86,74.52
63052,NaN,72046836,PHENTOLAMINE INJ 5MG 72046836,J2760,0999,932.88,746.30,699.66,792.95,792.95,792.95,792.95,792.95,699.66,746.30
63053,NaN,72078908,ROPIVACAINE 1MG 400MG 72078908,J2795,0999,94.18,75.34,70.64,80.05,80.05,80.05,80.05,80.05,70.64,75.34
63054,NaN,72078758,BILVALIRUDIN INJ 1MG 20MG 72078758,J0583,0999,94.50,75.60,70.88,80.33,80.33,80.33,80.33,80.33,70.88,75.60
63055,NaN,72000048,HEPATITIS B VAC 1ML 90731 72000048,90746,0999,99.80,79.84,74.85,84.83,84.83,84.83,84.83,84.83,74.85,79.84

In [10]:
from helpers import cleanup_values

money_columns = df_mid1.columns[5:]
df_mid1[money_columns] = df_mid1[money_columns].apply(cleanup_values)
df_mid1

,additional_generic_notes,local_code,description,hcpcs_cpt,rev_code,Gross Charge/Unit,Cash Price,MinRate,MaxRate,Beech Street,Excellus-RMSCO,HRGi,PHCS,UHC Commercial IP,UHC Commercial OP
0,NaN,0656D3NPX,RMBD PRIVATE,NaN,0111,2890.00,2312.00,2167.50,2456.50,2456.50,2456.50,2456.50,2456.50,2167.50,2312.00
1,NaN,0656D3NPXALC,RMBD PRIVATE ALC,NaN,0111,2890.00,2312.00,2167.50,2456.50,2456.50,2456.50,2456.50,2456.50,2167.50,2312.00
2,NaN,0656PX,RMBD PRIVATE,NaN,0111,2890.00,2312.00,2167.50,2456.50,2456.50,2456.50,2456.50,2456.50,2167.50,2312.00
3,NaN,0656PXALC,RMBD PRIVATE ALC,NaN,0111,2890.00,2312.00,2167.50,2456.50,2456.50,2456.50,2456.50,2456.50,2167.50,2312.00
4,NaN,8535PX,RMBD PRIVATE,NaN,0111,2890.00,2312.00,2167.50,2456.50,2456.50,2456.50,2456.50,2456.50,2167.50,2312.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63051,NaN,72099182,METHYLDOPATE INJ 250MG 72099182,J0210,0999,93.15,74.52,69.86,79.18,79.18,79.18,79.18,79.18,69.86,74.52
63052,NaN,72046836,PHENTOLAMINE INJ 5MG 72046836,J2760,0999,932.88,746.30,699.66,792.95,792.95,792.95,792.95,792.95,699.66,746.30
63053,NaN,72078908,ROPIVACAINE 1MG 400MG 72078908,J2795,0999,94.18,75.34,70.64,80.05,80.05,80.05,80.05,80.05,70.64,75.34
63054,NaN,72078758,BILVALIRUDIN INJ 1MG 20MG 72078758,J0583,0999,94.50,75.60,70.88,80.33,80.33,80.33,80.33,80.33,70.88,75.60
63055,NaN,72000048,HEPATITIS B VAC 1ML 90731 72000048,90746,0999,99.80,79.84,74.85,84.83,84.83,84.83,84.83,84.83,74.85,79.84

In [11]:
remaining_columns = df_mid1.columns[:5]
df_mid1 = pd.melt(df_mid1, id_vars=remaining_columns, var_name='payer_name', value_name='standard_charge')
df_mid1

,additional_generic_notes,local_code,description,hcpcs_cpt,rev_code,payer_name,standard_charge
0,NaN,0656D3NPX,RMBD PRIVATE,NaN,0111,Gross Charge/Unit,2890.00
1,NaN,0656D3NPXALC,RMBD PRIVATE ALC,NaN,0111,Gross Charge/Unit,2890.00
2,NaN,0656PX,RMBD PRIVATE,NaN,0111,Gross Charge/Unit,2890.00
3,NaN,0656PXALC,RMBD PRIVATE ALC,NaN,0111,Gross Charge/Unit,2890.00
4,NaN,8535PX,RMBD PRIVATE,NaN,0111,Gross Charge/Unit,2890.00
...,...,...,...,...,...,...,...
630555,NaN,72099182,METHYLDOPATE INJ 250MG 72099182,J0210,0999,UHC Commercial OP,74.52
630556,NaN,72046836,PHENTOLAMINE INJ 5MG 72046836,J2760,0999,UHC Commercial OP,746.3
630557,NaN,72078908,ROPIVACAINE 1MG 400MG 72078908,J2795,0999,UHC Commercial OP,75.34
630558,NaN,72078758,BILVALIRUDIN INJ 1MG 20MG 72078758,J0583,0999,UHC Commercial OP,75.6
630559,NaN,72000048,HEPATITIS B VAC 1ML 90731 72000048,90746,0999,UHC Commercial OP,79.84

In [12]:
def payer_category_from_payer_name(payer_name):
    if payer_name == "Gross Charge/Unit":
        return "gross"
    elif payer_name == "Cash Price":
        return "cash"
    elif payer_name == "MinRate":
        return "min"
    elif payer_name == "MaxRate":
        return "max"

    return "payer"

df_mid1['payer_category'] = df_mid1['payer_name'].apply(payer_category_from_payer_name)
df_mid1[['payer_name', 'payer_category']].value_counts()

payer_name         payer_category
Beech Street       payer             63056
Cash Price         cash              63056
Excellus-RMSCO     payer             63056
Gross Charge/Unit  gross             63056
HRGi               payer             63056
MaxRate            max               63056
MinRate            min               63056
PHCS               payer             63056
UHC Commercial IP  payer             63056
UHC Commercial OP  payer             63056
Name: count, dtype: int64

In [13]:
df_mid1.loc[df_mid1['payer_name'].str.endswith(' IP'), 'setting'] = 'inpatient'
df_mid1.loc[df_mid1['payer_name'].str.endswith(' OP'), 'setting'] = 'outpatient'
df_mid1[['payer_name', 'setting']].value_counts()

payer_name         setting
UHC Commercial IP  inpatient     63056
UHC Commercial OP  outpatient    63056
Name: count, dtype: int64

In [14]:
df_mid1['hospital_id'] = ccn
df_mid1['line_type'] = None
df_mid1['code'] = None
df_mid1['ms_drg'] = None
df_mid1['apr_drg'] = None
df_mid1['eapg'] = None
df_mid1['modifiers'] = None
df_mid1['alt_hcpcs_cpt'] = None
df_mid1['thru'] = None
df_mid1['apc'] = None
df_mid1['icd'] = None
df_mid1['ndc'] = None
df_mid1['drug_hcpcs_multiplier'] = None
df_mid1['drug_quantity'] = None
df_mid1['drug_unit_of_measurement'] = None
df_mid1['drug_type_of_measurement'] = None
df_mid1['billing_class'] = None
df_mid1['plan_name'] = None
df_mid1['standard_charge_percent'] = None
df_mid1['contracting_method'] = None
df_mid1['additional_payer_specific_notes'] = None

df_mid1

,additional_generic_notes,local_code,description,hcpcs_cpt,rev_code,payer_name,standard_charge,payer_category,setting,hospital_id,...,ndc,drug_hcpcs_multiplier,drug_quantity,drug_unit_of_measurement,drug_type_of_measurement,billing_class,plan_name,standard_charge_percent,contracting_method,additional_payer_specific_notes
0,NaN,0656D3NPX,RMBD PRIVATE,NaN,0111,Gross Charge/Unit,2890.00,gross,NaN,330013,...,None,None,None,None,None,None,None,None,None,None
1,NaN,0656D3NPXALC,RMBD PRIVATE ALC,NaN,0111,Gross Charge/Unit,2890.00,gross,NaN,330013,...,None,None,None,None,None,None,None,None,None,None
2,NaN,0656PX,RMBD PRIVATE,NaN,0111,Gross Charge/Unit,2890.00,gross,NaN,330013,...,None,None,None,None,None,None,None,None,None,None
3,NaN,0656PXALC,RMBD PRIVATE ALC,NaN,0111,Gross Charge/Unit,2890.00,gross,NaN,330013,...,None,None,None,None,None,None,None,None,None,None
4,NaN,8535PX,RMBD PRIVATE,NaN,0111,Gross Charge/Unit,2890.00,gross,NaN,330013,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
630555,NaN,72099182,METHYLDOPATE INJ 250MG 72099182,J0210,0999,UHC Commercial OP,74.52,payer,outpatient,330013,...,None,None,None,None,None,None,None,None,None,None
630556,NaN,72046836,PHENTOLAMINE INJ 5MG 72046836,J2760,0999,UHC Commercial OP,746.3,payer,outpatient,330013,...,None,None,None,None,None,None,None,None,None,None
630557,NaN,72078908,ROPIVACAINE 1MG 400MG 72078908,J2795,0999,UHC Commercial OP,75.34,payer,outpatient,330013,...,None,None,None,None,None,None,None,None,None,None
630558,NaN,72078758,BILVALIRUDIN INJ 1MG 20MG 72078758,J0583,0999,UHC Commercial OP,75.6,payer,outpatient,330013,...,None,None,None,None,None,None,None,None,None,None
630559,NaN,72000048,HEPATITIS B VAC 1ML 90731 72000048,90746,0999,UHC Commercial OP,79.84,payer,outpatient,330013,...,None,None,None,None,None,None,None,None,None,None

In [15]:
df_mid1 = df_mid1.dropna(subset=['standard_charge'], axis=0)

df_out1 = pd.DataFrame(df_mid1[TARGET_COLUMNS])
df_out1

,hospital_id,line_type,description,rev_code,local_code,code,ms_drg,apr_drg,eapg,hcpcs_cpt,...,billing_class,setting,payer_category,payer_name,plan_name,standard_charge,standard_charge_percent,contracting_method,additional_generic_notes,additional_payer_specific_notes
0,330013,None,RMBD PRIVATE,0111,0656D3NPX,None,None,None,None,NaN,...,None,NaN,gross,Gross Charge/Unit,None,2890.00,None,None,NaN,None
1,330013,None,RMBD PRIVATE ALC,0111,0656D3NPXALC,None,None,None,None,NaN,...,None,NaN,gross,Gross Charge/Unit,None,2890.00,None,None,NaN,None
2,330013,None,RMBD PRIVATE,0111,0656PX,None,None,None,None,NaN,...,None,NaN,gross,Gross Charge/Unit,None,2890.00,None,None,NaN,None
3,330013,None,RMBD PRIVATE ALC,0111,0656PXALC,None,None,None,None,NaN,...,None,NaN,gross,Gross Charge/Unit,None,2890.00,None,None,NaN,None
4,330013,None,RMBD PRIVATE,0111,8535PX,None,None,None,None,NaN,...,None,NaN,gross,Gross Charge/Unit,None,2890.00,None,None,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
630555,330013,None,METHYLDOPATE INJ 250MG 72099182,0999,72099182,None,None,None,None,J0210,...,None,outpatient,payer,UHC Commercial OP,None,74.52,None,None,NaN,None
630556,330013,None,PHENTOLAMINE INJ 5MG 72046836,0999,72046836,None,None,None,None,J2760,...,None,outpatient,payer,UHC Commercial OP,None,746.3,None,None,NaN,None
630557,330013,None,ROPIVACAINE 1MG 400MG 72078908,0999,72078908,None,None,None,None,J2795,...,None,outpatient,payer,UHC Commercial OP,None,75.34,None,None,NaN,None
630558,330013,None,BILVALIRUDIN INJ 1MG 20MG 72078758,0999,72078758,None,None,None,None,J0583,...,None,outpatient,payer,UHC Commercial OP,None,75.6,None,None,NaN,None
630559,330013,None,HEPATITIS B VAC 1ML 90731 72000048,0999,72000048,None,None,None,None,90746,...,None,outpatient,payer,UHC Commercial OP,None,79.84,None,None,NaN,None

In [19]:
df_out1.to_csv('rate_' + ccn + '_tbl1.csv', index=False)

In [18]:
df_in2 = pd.DataFrame(df_in.iloc[delim_idx+1:])
df_in2.columns = df_in2.iloc[0]
df_in2 = df_in2.iloc[1:]
df_in2.drop(columns=df_in2.columns[-4:], axis=1, inplace=True)
df_in2

63057,Payer Name,CodeType,Code,Description,Service,ReimburseType,Rate,Deidentified Min Rate,Deidentified Max Rate,ServiceType,NaN
63058,Aetna Commercial,DRG,MS-001,Heart Transplant Or Implant Of Heart Assist Sy...,Medical/Surgical,Relative Weights,746434.57,169204.29,848015.00,IP,NaN
63059,Aetna Commercial,DRG,MS-002,Heart Transplant Or Implant Of Heart Assist Sy...,Medical/Surgical,Relative Weights,357306.61,81114.03,848015.00,IP,NaN
63060,Aetna Commercial,DRG,MS-003,Ecmo Or Tracheostomy With Mv >96 Hours Or Prin...,Medical/Surgical,Relative Weights,536687.89,121722.12,536687.89,IP,NaN
63061,Aetna Commercial,DRG,MS-004,Tracheostomy With Mv >96 Hours Or Principal Di...,Medical/Surgical,Relative Weights,364164.68,82666.55,364164.68,IP,NaN
63062,Aetna Commercial,DRG,MS-005,Liver Transplant With Mcc Or Intestinal Transp...,Medical/Surgical,Relative Weights,302513.64,68710.07,302513.64,IP,NaN
...,...,...,...,...,...,...,...,...,...,...,...
387081,United The Empire Plan,CPT,97162,Pt eval mod complex 30 min,NaN,Straight Discount,80.00%,80.00%,80.00%,OP,NaN
387082,United The Empire Plan,CPT,97163,Pt eval high complex 45 min,NaN,Straight Discount,80.00%,80.00%,80.00%,OP,NaN
387083,United The Empire Plan,CPT,97165,Ot eval low complex 30 min,NaN,Straight Discount,80.00%,80.00%,80.00%,OP,NaN
387084,United The Empire Plan,CPT,97166,Ot eval mod complex 45 min,NaN,Straight Discount,80.00%,80.00%,80.00%,OP,NaN
387085,United The Empire Plan,CPT,U0004,Cov-19 test non-cdc hgh thru,NaN,Straight Discount,80.00%,80.00%,80.00%,OP,NaN