In [1]:
import pandas as pd

In [2]:
TARGET_COLUMNS = [ 
    'hospital_ccn',
    'hospital_ein',
    'code_type',
    'internal_code',
    'description',
    'code_orig',
    'code_prefix',
    'code',
    'modifier',
    'ndc',
    'ndc_num_hcpcs_doses',
    'ndc_quantity_desc',
    'apc',
    'rev_code',
    'rev_desc',
    'billing_class',
    'patient_class',
    'payer_category',
    'payer_orig',
    'payer_name',
    'plan_orig',
    'plan_name',
    'plan_id',
    'plan_type',
    'rate',
    'rate_method',
    'rate_desc',
    'filename',
    'file_last_updated',
    'url',
    'permalink'
]

In [3]:
ccn = "104024"
ein = "591101553"
filename = "Hospital-Standard-Charges.csv"
url = "http://05cdc38.rcomhost.com/CoC/wp-content/uploads/2021/01/Hospital-Standard-Charges.csv"

In [4]:
df_in = pd.read_csv(filename, header=3)
df_in

,Payer,Service,RevCode,NDC,Gross Charge,Negotiated Rate,Discounted Cash Rate,De-Identified Lowest,De-Identified Highest
0,Aetna,Per Diem Semi-Private,124,-,"$1,500",$822,NaN,$575,"$1,015"
1,Aetna International,Per Diem Semi-Private,124,-,"$1,500",$735,NaN,$575,"$1,015"
2,Ambetter,Per Diem Semi-Private,124,-,"$1,500",$790,NaN,$575,"$1,015"
3,Beacon,Per Diem Semi-Private,124,-,"$1,500",$790,NaN,$575,"$1,015"
4,Beacon Health Options,Per Diem Semi-Private,124,-,"$1,500",$790,NaN,$575,"$1,015"
5,Blue Cross/Blue Shield Of Florida,Per Diem Semi-Private,124,-,"$1,500",$790,NaN,$575,"$1,015"
6,Blue Cross/Blue Shield Of Florida,Per Diem Semi-Private,124,-,"$1,500",$790,NaN,$575,"$1,015"
7,Boon-Chapman,Per Diem Semi-Private,124,-,"$1,500",$590,NaN,$575,"$1,015"
8,Cenpatico Sunshine State Health Plan,Per Diem Semi-Private,124,-,"$1,500",$790,NaN,$575,"$1,015"
9,ChampusVA,Per Diem Semi-Private,124,-,"$1,500",$955,NaN,$575,"$1,015"
10,Cigna,Per Diem Semi-Private,124,-,"$1,500",$790,NaN,$575,"$1,015"
11,CommonWealth Care Alliance,Per Diem Semi-Private,124,-,"$1,500",$825,NaN,$575,"$1,015"
12,Consolidated HP (Cigna),Per Diem Semi-Private,124,-,"$1,500",$625,NaN,$575,"$1,015"
13,Continental Benefits,Per Diem Semi-Private,124,-,"$1,500",$935,NaN,$575,"$1,015"
14,Cypress Benefits Administrators,Per Diem Semi-Private,124,-,"$1,500","$1,015",NaN,$575,"$1,015"
15,Florida Health Care Plan,Per Diem Semi-Private,124,-,"$1,500",$845,NaN,$575,"$1,015"
16,Florida Health Care Plans,Per Diem Semi-Private,124,-,"$1,500",$845,NaN,$575,"$1,015"
17,GEHA,Per Diem Semi-Private,124,-,"$1,500",$795,NaN,$575,"$1,015"
18,Health First,Per Diem Semi-Private,124,-,"$1,500",$955,NaN,$575,"$1,015"
19,Health Net Tricare West,Per Diem Semi-Private,124,-,"$1,500",$755,NaN,$575,"$1,015"
20,Humana Medical Claims,Per Diem Semi-Private,124,-,"$1,500",$720,NaN,$575,"$1,015"
21,Kaiser Permanente (So California only),Per Diem Semi-Private,124,-,"$1,500",$700,NaN,$575,"$1,015"
22,Magellan Careplus,Per Diem Semi-Private,124,-,"$1,500",$735,NaN,$575,"$1,015"
23,Magellan H1st,Per Diem Semi-Private,124,-,"$1,500",$700,NaN,$575,"$1,015"
24,Magellan H1st,Per Diem Semi-Private,124,-,"$1,500",$700,NaN,$575,"$1,015"
25,MagnaCare,Per Diem Semi-Private,124,-,"$1,500",$640,NaN,$575,"$1,015"
26,MCC Commerical,Per Diem Semi-Private,124,-,"$1,500",$830,NaN,$575,"$1,015"
27,Medicare A & B,Per Diem Semi-Private,124,-,"$1,500",$780,NaN,$575,"$1,015"
28,Meritain Health,Per Diem Semi-Private,124,-,"$1,500",$785,NaN,$575,"$1,015"
29,National Association Of Letter Carriers,Per Diem Semi-Private,124,-,"$1,500",$710,NaN,$575,"$1,015"
30,Optum/UMR/GEHA,Per Diem Semi-Private,124,-,"$1,500",$865,NaN,$575,"$1,015"
31,Tricare East,Per Diem Semi-Private,124,-,"$1,500",$700,NaN,$575,"$1,015"
32,United Behavioral Health,Per Diem Semi-Private,124,-,"$1,500",$865,NaN,$575,"$1,015"
33,United Behavioral Health,Per Diem Semi-Private,124,-,"$1,500",$865,NaN,$575,"$1,015"
34,United Behavioral Health,Per Diem Semi-Private,124,-,"$1,500",$865,NaN,$575,"$1,015"
35,United Health Care,Per Diem Semi-Private,124,-,"$1,500",$865,NaN,$575,"$1,015"
36,VA by Optum,Per Diem Semi-Private,124,-,"$1,500",$860,NaN,$575,"$1,015"
37,VA Fee Basis,Per Diem Semi-Private,124,-,"$1,500",$705,NaN,$575,"$1,015"
38,Value Options,Per Diem Semi-Private,124,-,"$1,500",$575,NaN,$575,"$1,015"
39,Wellcare Commercial,Per Diem Semi-Private,124,-,"$1,500",$745,NaN,$575,"$1,015"
40,Wellcare Medicare,Per Diem Semi-Private,124,-,"$1,500",$675,NaN,$575,"$1,015"

In [5]:
df_mid = pd.DataFrame(df_in)
df_mid = df_mid.rename(columns={
    'Payer': 'payer_orig',
    'Service': 'description',
    'RevCode': 'rev_code',
    'NDC': 'ndc',
    #'Gross Charge': 'gross',
    #'Negotiated Rate': 'rate',
    #'Discounted Cash Rate': 'cash',
    #'De-Identified Lowest': 'min',
    #'De-Identified Highest': 'max'
})
df_mid

,payer_orig,description,rev_code,ndc,Gross Charge,Negotiated Rate,Discounted Cash Rate,De-Identified Lowest,De-Identified Highest
0,Aetna,Per Diem Semi-Private,124,-,"$1,500",$822,NaN,$575,"$1,015"
1,Aetna International,Per Diem Semi-Private,124,-,"$1,500",$735,NaN,$575,"$1,015"
2,Ambetter,Per Diem Semi-Private,124,-,"$1,500",$790,NaN,$575,"$1,015"
3,Beacon,Per Diem Semi-Private,124,-,"$1,500",$790,NaN,$575,"$1,015"
4,Beacon Health Options,Per Diem Semi-Private,124,-,"$1,500",$790,NaN,$575,"$1,015"
5,Blue Cross/Blue Shield Of Florida,Per Diem Semi-Private,124,-,"$1,500",$790,NaN,$575,"$1,015"
6,Blue Cross/Blue Shield Of Florida,Per Diem Semi-Private,124,-,"$1,500",$790,NaN,$575,"$1,015"
7,Boon-Chapman,Per Diem Semi-Private,124,-,"$1,500",$590,NaN,$575,"$1,015"
8,Cenpatico Sunshine State Health Plan,Per Diem Semi-Private,124,-,"$1,500",$790,NaN,$575,"$1,015"
9,ChampusVA,Per Diem Semi-Private,124,-,"$1,500",$955,NaN,$575,"$1,015"
10,Cigna,Per Diem Semi-Private,124,-,"$1,500",$790,NaN,$575,"$1,015"
11,CommonWealth Care Alliance,Per Diem Semi-Private,124,-,"$1,500",$825,NaN,$575,"$1,015"
12,Consolidated HP (Cigna),Per Diem Semi-Private,124,-,"$1,500",$625,NaN,$575,"$1,015"
13,Continental Benefits,Per Diem Semi-Private,124,-,"$1,500",$935,NaN,$575,"$1,015"
14,Cypress Benefits Administrators,Per Diem Semi-Private,124,-,"$1,500","$1,015",NaN,$575,"$1,015"
15,Florida Health Care Plan,Per Diem Semi-Private,124,-,"$1,500",$845,NaN,$575,"$1,015"
16,Florida Health Care Plans,Per Diem Semi-Private,124,-,"$1,500",$845,NaN,$575,"$1,015"
17,GEHA,Per Diem Semi-Private,124,-,"$1,500",$795,NaN,$575,"$1,015"
18,Health First,Per Diem Semi-Private,124,-,"$1,500",$955,NaN,$575,"$1,015"
19,Health Net Tricare West,Per Diem Semi-Private,124,-,"$1,500",$755,NaN,$575,"$1,015"
20,Humana Medical Claims,Per Diem Semi-Private,124,-,"$1,500",$720,NaN,$575,"$1,015"
21,Kaiser Permanente (So California only),Per Diem Semi-Private,124,-,"$1,500",$700,NaN,$575,"$1,015"
22,Magellan Careplus,Per Diem Semi-Private,124,-,"$1,500",$735,NaN,$575,"$1,015"
23,Magellan H1st,Per Diem Semi-Private,124,-,"$1,500",$700,NaN,$575,"$1,015"
24,Magellan H1st,Per Diem Semi-Private,124,-,"$1,500",$700,NaN,$575,"$1,015"
25,MagnaCare,Per Diem Semi-Private,124,-,"$1,500",$640,NaN,$575,"$1,015"
26,MCC Commerical,Per Diem Semi-Private,124,-,"$1,500",$830,NaN,$575,"$1,015"
27,Medicare A & B,Per Diem Semi-Private,124,-,"$1,500",$780,NaN,$575,"$1,015"
28,Meritain Health,Per Diem Semi-Private,124,-,"$1,500",$785,NaN,$575,"$1,015"
29,National Association Of Letter Carriers,Per Diem Semi-Private,124,-,"$1,500",$710,NaN,$575,"$1,015"
30,Optum/UMR/GEHA,Per Diem Semi-Private,124,-,"$1,500",$865,NaN,$575,"$1,015"
31,Tricare East,Per Diem Semi-Private,124,-,"$1,500",$700,NaN,$575,"$1,015"
32,United Behavioral Health,Per Diem Semi-Private,124,-,"$1,500",$865,NaN,$575,"$1,015"
33,United Behavioral Health,Per Diem Semi-Private,124,-,"$1,500",$865,NaN,$575,"$1,015"
34,United Behavioral Health,Per Diem Semi-Private,124,-,"$1,500",$865,NaN,$575,"$1,015"
35,United Health Care,Per Diem Semi-Private,124,-,"$1,500",$865,NaN,$575,"$1,015"
36,VA by Optum,Per Diem Semi-Private,124,-,"$1,500",$860,NaN,$575,"$1,015"
37,VA Fee Basis,Per Diem Semi-Private,124,-,"$1,500",$705,NaN,$575,"$1,015"
38,Value Options,Per Diem Semi-Private,124,-,"$1,500",$575,NaN,$575,"$1,015"
39,Wellcare Commercial,Per Diem Semi-Private,124,-,"$1,500",$745,NaN,$575,"$1,015"
40,Wellcare Medicare,Per Diem Semi-Private,124,-,"$1,500",$675,NaN,$575,"$1,015"

In [6]:
columns = df_mid.columns.to_list()
money_columns = ['Gross Charge', 'Discounted Cash Rate', 'De-Identified Lowest', 'De-Identified Highest', 'Negotiated Rate']
remaining_cols = list(set(columns) - set(money_columns))
df_mid = pd.melt(df_mid, id_vars=remaining_cols)
df_mid['variable'] = df_mid['variable'].replace('rate', 'payer')
df_mid = df_mid.rename(columns={
    'variable': 'payer_category',
    'value': 'rate',
})
df_mid['payer_orig'] = df_mid.apply(lambda row: row['payer_orig'] if row['payer_category'] == 'Negotiated Rate' else row['payer_category'], 
                                    axis=1)
df_mid['payer_category'] = df_mid['payer_category'].replace(
    'Gross Charge', 'gross').replace('Discounted Cash Rate', 'cash').replace(
    'De-Identified Lowest', 'min').replace('De-Identified Highest').replace(
    'Negotiated Rate', 'payer')
df_mid['rate'] = df_mid['rate'].astype(str)
df_mid['rate'] = df_mid['rate'].apply(lambda rate: rate.replace("$", "").replace(",", ""))
df_mid['ndc'] = 'na'
df_mid['rev_code'] = df_mid['rev_code'].astype(str)
df_mid['rev_code'] = df_mid['rev_code'].apply(lambda rev_code: "0" + rev_code)
df_mid

,description,ndc,rev_code,payer_orig,payer_category,rate
0,Per Diem Semi-Private,na,0124,Gross Charge,gross,1500
1,Per Diem Semi-Private,na,0124,Gross Charge,gross,1500
2,Per Diem Semi-Private,na,0124,Gross Charge,gross,1500
3,Per Diem Semi-Private,na,0124,Gross Charge,gross,1500
4,Per Diem Semi-Private,na,0124,Gross Charge,gross,1500
...,...,...,...,...,...,...
200,Per Diem Semi-Private,na,0124,De-Identified Highest,min,1015
201,Per Diem Semi-Private,na,0124,De-Identified Highest,min,1015
202,Per Diem Semi-Private,na,0124,De-Identified Highest,min,1015
203,Per Diem Semi-Private,na,0124,De-Identified Highest,min,1015
204,Per Diem Semi-Private,na,0124,De-Identified Highest,min,1015

In [7]:
df_mid['plan_orig'] = 'na'
df_mid['billing_class'] = 'na'
df_mid['patient_class'] = 'na'
df_mid['internal_code'] = 'na'
df_mid['code_prefix'] = 'none'
df_mid['code'] = df_mid['rev_code']
df_mid['modifier'] = 'na'
df_mid

,description,ndc,rev_code,payer_orig,payer_category,rate,plan_orig,billing_class,patient_class,internal_code,code_prefix,code,modifier
0,Per Diem Semi-Private,na,0124,Gross Charge,gross,1500,na,na,na,na,none,0124,na
1,Per Diem Semi-Private,na,0124,Gross Charge,gross,1500,na,na,na,na,none,0124,na
2,Per Diem Semi-Private,na,0124,Gross Charge,gross,1500,na,na,na,na,none,0124,na
3,Per Diem Semi-Private,na,0124,Gross Charge,gross,1500,na,na,na,na,none,0124,na
4,Per Diem Semi-Private,na,0124,Gross Charge,gross,1500,na,na,na,na,none,0124,na
...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,Per Diem Semi-Private,na,0124,De-Identified Highest,min,1015,na,na,na,na,none,0124,na
201,Per Diem Semi-Private,na,0124,De-Identified Highest,min,1015,na,na,na,na,none,0124,na
202,Per Diem Semi-Private,na,0124,De-Identified Highest,min,1015,na,na,na,na,none,0124,na
203,Per Diem Semi-Private,na,0124,De-Identified Highest,min,1015,na,na,na,na,none,0124,na
204,Per Diem Semi-Private,na,0124,De-Identified Highest,min,1015,na,na,na,na,none,0124,na

In [8]:
df_mid[df_mid['payer_category'] == 'cash']

,description,ndc,rev_code,payer_orig,payer_category,rate,plan_orig,billing_class,patient_class,internal_code,code_prefix,code,modifier
82,Per Diem Semi-Private,na,0124,Discounted Cash Rate,cash,nan,na,na,na,na,none,0124,na
83,Per Diem Semi-Private,na,0124,Discounted Cash Rate,cash,nan,na,na,na,na,none,0124,na
84,Per Diem Semi-Private,na,0124,Discounted Cash Rate,cash,nan,na,na,na,na,none,0124,na
85,Per Diem Semi-Private,na,0124,Discounted Cash Rate,cash,nan,na,na,na,na,none,0124,na
86,Per Diem Semi-Private,na,0124,Discounted Cash Rate,cash,nan,na,na,na,na,none,0124,na
87,Per Diem Semi-Private,na,0124,Discounted Cash Rate,cash,nan,na,na,na,na,none,0124,na
88,Per Diem Semi-Private,na,0124,Discounted Cash Rate,cash,nan,na,na,na,na,none,0124,na
89,Per Diem Semi-Private,na,0124,Discounted Cash Rate,cash,nan,na,na,na,na,none,0124,na
90,Per Diem Semi-Private,na,0124,Discounted Cash Rate,cash,nan,na,na,na,na,none,0124,na
91,Per Diem Semi-Private,na,0124,Discounted Cash Rate,cash,nan,na,na,na,na,none,0124,na
92,Per Diem Semi-Private,na,0124,Discounted Cash Rate,cash,nan,na,na,na,na,none,0124,na
93,Per Diem Semi-Private,na,0124,Discounted Cash Rate,cash,nan,na,na,na,na,none,0124,na
94,Per Diem Semi-Private,na,0124,Discounted Cash Rate,cash,nan,na,na,na,na,none,0124,na
95,Per Diem Semi-Private,na,0124,Discounted Cash Rate,cash,nan,na,na,na,na,none,0124,na
96,Per Diem Semi-Private,na,0124,Discounted Cash Rate,cash,nan,na,na,na,na,none,0124,na
97,Per Diem Semi-Private,na,0124,Discounted Cash Rate,cash,nan,na,na,na,na,none,0124,na
98,Per Diem Semi-Private,na,0124,Discounted Cash Rate,cash,nan,na,na,na,na,none,0124,na
99,Per Diem Semi-Private,na,0124,Discounted Cash Rate,cash,nan,na,na,na,na,none,0124,na
100,Per Diem Semi-Private,na,0124,Discounted Cash Rate,cash,nan,na,na,na,na,none,0124,na
101,Per Diem Semi-Private,na,0124,Discounted Cash Rate,cash,nan,na,na,na,na,none,0124,na
102,Per Diem Semi-Private,na,0124,Discounted Cash Rate,cash,nan,na,na,na,na,none,0124,na
103,Per Diem Semi-Private,na,0124,Discounted Cash Rate,cash,nan,na,na,na,na,none,0124,na
104,Per Diem Semi-Private,na,0124,Discounted Cash Rate,cash,nan,na,na,na,na,none,0124,na
105,Per Diem Semi-Private,na,0124,Discounted Cash Rate,cash,nan,na,na,na,na,none,0124,na
106,Per Diem Semi-Private,na,0124,Discounted Cash Rate,cash,nan,na,na,na,na,none,0124,na
107,Per Diem Semi-Private,na,0124,Discounted Cash Rate,cash,nan,na,na,na,na,none,0124,na
108,Per Diem Semi-Private,na,0124,Discounted Cash Rate,cash,nan,na,na,na,na,none,0124,na
109,Per Diem Semi-Private,na,0124,Discounted Cash Rate,cash,nan,na,na,na,na,none,0124,na
110,Per Diem Semi-Private,na,0124,Discounted Cash Rate,cash,nan,na,na,na,na,none,0124,na
111,Per Diem Semi-Private,na,0124,Discounted Cash Rate,cash,nan,na,na,na,na,none,0124,na
112,Per Diem Semi-Private,na,0124,Discounted Cash Rate,cash,nan,na,na,na,na,none,0124,na
113,Per Diem Semi-Private,na,0124,Discounted Cash Rate,cash,nan,na,na,na,na,none,0124,na
114,Per Diem Semi-Private,na,0124,Discounted Cash Rate,cash,nan,na,na,na,na,none,0124,na
115,Per Diem Semi-Private,na,0124,Discounted Cash Rate,cash,nan,na,na,na,na,none,0124,na
116,Per Diem Semi-Private,na,0124,Discounted Cash Rate,cash,nan,na,na,na,na,none,0124,na
117,Per Diem Semi-Private,na,0124,Discounted Cash Rate,cash,nan,na,na,na,na,none,0124,na
118,Per Diem Semi-Private,na,0124,Discounted Cash Rate,cash,nan,na,na,na,na,none,0124,na
119,Per Diem Semi-Private,na,0124,Discounted Cash Rate,cash,nan,na,na,na,na,none,0124,na
120,Per Diem Semi-Private,na,0124,Discounted Cash Rate,cash,nan,na,na,na,na,none,0124,na
121,Per Diem Semi-Private,na,0124,Discounted Cash Rate,cash,nan,na,na,na,na,none,0124,na
122,Per Diem Semi-Private,na,0124,Discounted Cash Rate,cash,nan,na,na,na,na,none,0124,na

In [9]:
df_mid = df_mid.dropna(subset=['rate'])
df_mid = df_mid[df_mid['rate'] != 'nan']
df_mid

,description,ndc,rev_code,payer_orig,payer_category,rate,plan_orig,billing_class,patient_class,internal_code,code_prefix,code,modifier
0,Per Diem Semi-Private,na,0124,Gross Charge,gross,1500,na,na,na,na,none,0124,na
1,Per Diem Semi-Private,na,0124,Gross Charge,gross,1500,na,na,na,na,none,0124,na
2,Per Diem Semi-Private,na,0124,Gross Charge,gross,1500,na,na,na,na,none,0124,na
3,Per Diem Semi-Private,na,0124,Gross Charge,gross,1500,na,na,na,na,none,0124,na
4,Per Diem Semi-Private,na,0124,Gross Charge,gross,1500,na,na,na,na,none,0124,na
...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,Per Diem Semi-Private,na,0124,De-Identified Highest,min,1015,na,na,na,na,none,0124,na
201,Per Diem Semi-Private,na,0124,De-Identified Highest,min,1015,na,na,na,na,none,0124,na
202,Per Diem Semi-Private,na,0124,De-Identified Highest,min,1015,na,na,na,na,none,0124,na
203,Per Diem Semi-Private,na,0124,De-Identified Highest,min,1015,na,na,na,na,none,0124,na
204,Per Diem Semi-Private,na,0124,De-Identified Highest,min,1015,na,na,na,na,none,0124,na

In [10]:
in_f = open(filename, "r")
date_line = in_f.read().split("\n")[1]
in_f.close()
date_line

'Prices Effective 01/01/2021,,,,,,,,'

In [11]:
updated_at = date_line.split("Effective ")[-1].split(",")[0]
day, month, year = updated_at.split("/")
updated_at = "{}-{}-{}".format(year, month, day)
df_mid['file_last_updated'] = updated_at
df_mid['hospital_ccn'] = ccn
df_mid['hospital_ein'] = ein[:2] + "-" + ein[2:]
df_mid['filename'] = filename
df_mid['url'] = url
df_mid

,description,ndc,rev_code,payer_orig,payer_category,rate,plan_orig,billing_class,patient_class,internal_code,code_prefix,code,modifier,file_last_updated,hospital_ccn,hospital_ein,filename,url
0,Per Diem Semi-Private,na,0124,Gross Charge,gross,1500,na,na,na,na,none,0124,na,2021-01-01,104024,59-1101553,Hospital-Standard-Charges.csv,http://05cdc38.rcomhost.com/CoC/wp-content/upl...
1,Per Diem Semi-Private,na,0124,Gross Charge,gross,1500,na,na,na,na,none,0124,na,2021-01-01,104024,59-1101553,Hospital-Standard-Charges.csv,http://05cdc38.rcomhost.com/CoC/wp-content/upl...
2,Per Diem Semi-Private,na,0124,Gross Charge,gross,1500,na,na,na,na,none,0124,na,2021-01-01,104024,59-1101553,Hospital-Standard-Charges.csv,http://05cdc38.rcomhost.com/CoC/wp-content/upl...
3,Per Diem Semi-Private,na,0124,Gross Charge,gross,1500,na,na,na,na,none,0124,na,2021-01-01,104024,59-1101553,Hospital-Standard-Charges.csv,http://05cdc38.rcomhost.com/CoC/wp-content/upl...
4,Per Diem Semi-Private,na,0124,Gross Charge,gross,1500,na,na,na,na,none,0124,na,2021-01-01,104024,59-1101553,Hospital-Standard-Charges.csv,http://05cdc38.rcomhost.com/CoC/wp-content/upl...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,Per Diem Semi-Private,na,0124,De-Identified Highest,min,1015,na,na,na,na,none,0124,na,2021-01-01,104024,59-1101553,Hospital-Standard-Charges.csv,http://05cdc38.rcomhost.com/CoC/wp-content/upl...
201,Per Diem Semi-Private,na,0124,De-Identified Highest,min,1015,na,na,na,na,none,0124,na,2021-01-01,104024,59-1101553,Hospital-Standard-Charges.csv,http://05cdc38.rcomhost.com/CoC/wp-content/upl...
202,Per Diem Semi-Private,na,0124,De-Identified Highest,min,1015,na,na,na,na,none,0124,na,2021-01-01,104024,59-1101553,Hospital-Standard-Charges.csv,http://05cdc38.rcomhost.com/CoC/wp-content/upl...
203,Per Diem Semi-Private,na,0124,De-Identified Highest,min,1015,na,na,na,na,none,0124,na,2021-01-01,104024,59-1101553,Hospital-Standard-Charges.csv,http://05cdc38.rcomhost.com/CoC/wp-content/upl...
204,Per Diem Semi-Private,na,0124,De-Identified Highest,min,1015,na,na,na,na,none,0124,na,2021-01-01,104024,59-1101553,Hospital-Standard-Charges.csv,http://05cdc38.rcomhost.com/CoC/wp-content/upl...

In [12]:
df_out = pd.DataFrame(columns=TARGET_COLUMNS)
df_out = df_out.append(df_mid)
df_out

/tmp/ipykernel_10480/1355504798.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_out = df_out.append(df_mid)

,hospital_ccn,hospital_ein,code_type,internal_code,description,code_orig,code_prefix,code,modifier,ndc,...,plan_name,plan_id,plan_type,rate,rate_method,rate_desc,filename,file_last_updated,url,permalink
0,104024,59-1101553,NaN,na,Per Diem Semi-Private,NaN,none,0124,na,na,...,NaN,NaN,NaN,1500,NaN,NaN,Hospital-Standard-Charges.csv,2021-01-01,http://05cdc38.rcomhost.com/CoC/wp-content/upl...,NaN
1,104024,59-1101553,NaN,na,Per Diem Semi-Private,NaN,none,0124,na,na,...,NaN,NaN,NaN,1500,NaN,NaN,Hospital-Standard-Charges.csv,2021-01-01,http://05cdc38.rcomhost.com/CoC/wp-content/upl...,NaN
2,104024,59-1101553,NaN,na,Per Diem Semi-Private,NaN,none,0124,na,na,...,NaN,NaN,NaN,1500,NaN,NaN,Hospital-Standard-Charges.csv,2021-01-01,http://05cdc38.rcomhost.com/CoC/wp-content/upl...,NaN
3,104024,59-1101553,NaN,na,Per Diem Semi-Private,NaN,none,0124,na,na,...,NaN,NaN,NaN,1500,NaN,NaN,Hospital-Standard-Charges.csv,2021-01-01,http://05cdc38.rcomhost.com/CoC/wp-content/upl...,NaN
4,104024,59-1101553,NaN,na,Per Diem Semi-Private,NaN,none,0124,na,na,...,NaN,NaN,NaN,1500,NaN,NaN,Hospital-Standard-Charges.csv,2021-01-01,http://05cdc38.rcomhost.com/CoC/wp-content/upl...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,104024,59-1101553,NaN,na,Per Diem Semi-Private,NaN,none,0124,na,na,...,NaN,NaN,NaN,1015,NaN,NaN,Hospital-Standard-Charges.csv,2021-01-01,http://05cdc38.rcomhost.com/CoC/wp-content/upl...,NaN
201,104024,59-1101553,NaN,na,Per Diem Semi-Private,NaN,none,0124,na,na,...,NaN,NaN,NaN,1015,NaN,NaN,Hospital-Standard-Charges.csv,2021-01-01,http://05cdc38.rcomhost.com/CoC/wp-content/upl...,NaN
202,104024,59-1101553,NaN,na,Per Diem Semi-Private,NaN,none,0124,na,na,...,NaN,NaN,NaN,1015,NaN,NaN,Hospital-Standard-Charges.csv,2021-01-01,http://05cdc38.rcomhost.com/CoC/wp-content/upl...,NaN
203,104024,59-1101553,NaN,na,Per Diem Semi-Private,NaN,none,0124,na,na,...,NaN,NaN,NaN,1015,NaN,NaN,Hospital-Standard-Charges.csv,2021-01-01,http://05cdc38.rcomhost.com/CoC/wp-content/upl...,NaN
204,104024,59-1101553,NaN,na,Per Diem Semi-Private,NaN,none,0124,na,na,...,NaN,NaN,NaN,1015,NaN,NaN,Hospital-Standard-Charges.csv,2021-01-01,http://05cdc38.rcomhost.com/CoC/wp-content/upl...,NaN

In [13]:
df_out.to_csv('104024.csv', index=False)