In [15]:
import pandas as pd

In [16]:
TARGET_COLUMNS = [
    "hospital_id",
    #'row_id',
    "line_type",
    "description",
    "rev_code",
    "local_code",
    "code",
    "ms_drg",
    "apr_drg",
    "eapg",
    "hcpcs_cpt",
    "modifiers",
    "alt_hcpcs_cpt",
    "thru",
    "apc",
    "icd",
    "ndc",
    "drug_hcpcs_multiplier",
    "drug_quantity",
    "drug_unit_of_measurement",
    "drug_type_of_measurement",
    "billing_class",
    "setting",
    "rate_category",
    "payer_name",
    "plan_name",
    "standard_charge",
    "standard_charge_percent",
    "contracting_method",
    "additional_generic_notes",
    "additional_payer_specific_notes",
]

In [17]:
ccn = "104024"
ein = "591101553"
filename = "Hospital-Standard-Charges.csv"
url = "http://05cdc38.rcomhost.com/CoC/wp-content/uploads/2021/01/Hospital-Standard-Charges.csv"

In [18]:
import subprocess

subprocess.run(["wget", "--no-clobber", url, "-O", filename])

File ‘Hospital-Standard-Charges.csv’ already there; not retrieving.

CompletedProcess(args=['wget', '--no-clobber', 'http://05cdc38.rcomhost.com/CoC/wp-content/uploads/2021/01/Hospital-Standard-Charges.csv', '-O', 'Hospital-Standard-Charges.csv'], returncode=1)

In [19]:
df_in = pd.read_csv(filename, header=3)
df_in

,Payer,Service,RevCode,NDC,Gross Charge,Negotiated Rate,Discounted Cash Rate,De-Identified Lowest,De-Identified Highest
0,Aetna,Per Diem Semi-Private,124,-,"$1,500",$822,NaN,$575,"$1,015"
1,Aetna International,Per Diem Semi-Private,124,-,"$1,500",$735,NaN,$575,"$1,015"
2,Ambetter,Per Diem Semi-Private,124,-,"$1,500",$790,NaN,$575,"$1,015"
3,Beacon,Per Diem Semi-Private,124,-,"$1,500",$790,NaN,$575,"$1,015"
4,Beacon Health Options,Per Diem Semi-Private,124,-,"$1,500",$790,NaN,$575,"$1,015"
5,Blue Cross/Blue Shield Of Florida,Per Diem Semi-Private,124,-,"$1,500",$790,NaN,$575,"$1,015"
6,Blue Cross/Blue Shield Of Florida,Per Diem Semi-Private,124,-,"$1,500",$790,NaN,$575,"$1,015"
7,Boon-Chapman,Per Diem Semi-Private,124,-,"$1,500",$590,NaN,$575,"$1,015"
8,Cenpatico Sunshine State Health Plan,Per Diem Semi-Private,124,-,"$1,500",$790,NaN,$575,"$1,015"
9,ChampusVA,Per Diem Semi-Private,124,-,"$1,500",$955,NaN,$575,"$1,015"
10,Cigna,Per Diem Semi-Private,124,-,"$1,500",$790,NaN,$575,"$1,015"
11,CommonWealth Care Alliance,Per Diem Semi-Private,124,-,"$1,500",$825,NaN,$575,"$1,015"
12,Consolidated HP (Cigna),Per Diem Semi-Private,124,-,"$1,500",$625,NaN,$575,"$1,015"
13,Continental Benefits,Per Diem Semi-Private,124,-,"$1,500",$935,NaN,$575,"$1,015"
14,Cypress Benefits Administrators,Per Diem Semi-Private,124,-,"$1,500","$1,015",NaN,$575,"$1,015"
15,Florida Health Care Plan,Per Diem Semi-Private,124,-,"$1,500",$845,NaN,$575,"$1,015"
16,Florida Health Care Plans,Per Diem Semi-Private,124,-,"$1,500",$845,NaN,$575,"$1,015"
17,GEHA,Per Diem Semi-Private,124,-,"$1,500",$795,NaN,$575,"$1,015"
18,Health First,Per Diem Semi-Private,124,-,"$1,500",$955,NaN,$575,"$1,015"
19,Health Net Tricare West,Per Diem Semi-Private,124,-,"$1,500",$755,NaN,$575,"$1,015"
20,Humana Medical Claims,Per Diem Semi-Private,124,-,"$1,500",$720,NaN,$575,"$1,015"
21,Kaiser Permanente (So California only),Per Diem Semi-Private,124,-,"$1,500",$700,NaN,$575,"$1,015"
22,Magellan Careplus,Per Diem Semi-Private,124,-,"$1,500",$735,NaN,$575,"$1,015"
23,Magellan H1st,Per Diem Semi-Private,124,-,"$1,500",$700,NaN,$575,"$1,015"
24,Magellan H1st,Per Diem Semi-Private,124,-,"$1,500",$700,NaN,$575,"$1,015"
25,MagnaCare,Per Diem Semi-Private,124,-,"$1,500",$640,NaN,$575,"$1,015"
26,MCC Commerical,Per Diem Semi-Private,124,-,"$1,500",$830,NaN,$575,"$1,015"
27,Medicare A & B,Per Diem Semi-Private,124,-,"$1,500",$780,NaN,$575,"$1,015"
28,Meritain Health,Per Diem Semi-Private,124,-,"$1,500",$785,NaN,$575,"$1,015"
29,National Association Of Letter Carriers,Per Diem Semi-Private,124,-,"$1,500",$710,NaN,$575,"$1,015"
30,Optum/UMR/GEHA,Per Diem Semi-Private,124,-,"$1,500",$865,NaN,$575,"$1,015"
31,Tricare East,Per Diem Semi-Private,124,-,"$1,500",$700,NaN,$575,"$1,015"
32,United Behavioral Health,Per Diem Semi-Private,124,-,"$1,500",$865,NaN,$575,"$1,015"
33,United Behavioral Health,Per Diem Semi-Private,124,-,"$1,500",$865,NaN,$575,"$1,015"
34,United Behavioral Health,Per Diem Semi-Private,124,-,"$1,500",$865,NaN,$575,"$1,015"
35,United Health Care,Per Diem Semi-Private,124,-,"$1,500",$865,NaN,$575,"$1,015"
36,VA by Optum,Per Diem Semi-Private,124,-,"$1,500",$860,NaN,$575,"$1,015"
37,VA Fee Basis,Per Diem Semi-Private,124,-,"$1,500",$705,NaN,$575,"$1,015"
38,Value Options,Per Diem Semi-Private,124,-,"$1,500",$575,NaN,$575,"$1,015"
39,Wellcare Commercial,Per Diem Semi-Private,124,-,"$1,500",$745,NaN,$575,"$1,015"
40,Wellcare Medicare,Per Diem Semi-Private,124,-,"$1,500",$675,NaN,$575,"$1,015"

In [20]:
df_mid = pd.DataFrame(df_in)
df_mid = df_mid.rename(columns={
    'Payer': 'payer_name',
    'Service': 'description',
    'RevCode': 'rev_code',
    'NDC': 'ndc',
})
df_mid

,payer_name,description,rev_code,ndc,Gross Charge,Negotiated Rate,Discounted Cash Rate,De-Identified Lowest,De-Identified Highest
0,Aetna,Per Diem Semi-Private,124,-,"$1,500",$822,NaN,$575,"$1,015"
1,Aetna International,Per Diem Semi-Private,124,-,"$1,500",$735,NaN,$575,"$1,015"
2,Ambetter,Per Diem Semi-Private,124,-,"$1,500",$790,NaN,$575,"$1,015"
3,Beacon,Per Diem Semi-Private,124,-,"$1,500",$790,NaN,$575,"$1,015"
4,Beacon Health Options,Per Diem Semi-Private,124,-,"$1,500",$790,NaN,$575,"$1,015"
5,Blue Cross/Blue Shield Of Florida,Per Diem Semi-Private,124,-,"$1,500",$790,NaN,$575,"$1,015"
6,Blue Cross/Blue Shield Of Florida,Per Diem Semi-Private,124,-,"$1,500",$790,NaN,$575,"$1,015"
7,Boon-Chapman,Per Diem Semi-Private,124,-,"$1,500",$590,NaN,$575,"$1,015"
8,Cenpatico Sunshine State Health Plan,Per Diem Semi-Private,124,-,"$1,500",$790,NaN,$575,"$1,015"
9,ChampusVA,Per Diem Semi-Private,124,-,"$1,500",$955,NaN,$575,"$1,015"
10,Cigna,Per Diem Semi-Private,124,-,"$1,500",$790,NaN,$575,"$1,015"
11,CommonWealth Care Alliance,Per Diem Semi-Private,124,-,"$1,500",$825,NaN,$575,"$1,015"
12,Consolidated HP (Cigna),Per Diem Semi-Private,124,-,"$1,500",$625,NaN,$575,"$1,015"
13,Continental Benefits,Per Diem Semi-Private,124,-,"$1,500",$935,NaN,$575,"$1,015"
14,Cypress Benefits Administrators,Per Diem Semi-Private,124,-,"$1,500","$1,015",NaN,$575,"$1,015"
15,Florida Health Care Plan,Per Diem Semi-Private,124,-,"$1,500",$845,NaN,$575,"$1,015"
16,Florida Health Care Plans,Per Diem Semi-Private,124,-,"$1,500",$845,NaN,$575,"$1,015"
17,GEHA,Per Diem Semi-Private,124,-,"$1,500",$795,NaN,$575,"$1,015"
18,Health First,Per Diem Semi-Private,124,-,"$1,500",$955,NaN,$575,"$1,015"
19,Health Net Tricare West,Per Diem Semi-Private,124,-,"$1,500",$755,NaN,$575,"$1,015"
20,Humana Medical Claims,Per Diem Semi-Private,124,-,"$1,500",$720,NaN,$575,"$1,015"
21,Kaiser Permanente (So California only),Per Diem Semi-Private,124,-,"$1,500",$700,NaN,$575,"$1,015"
22,Magellan Careplus,Per Diem Semi-Private,124,-,"$1,500",$735,NaN,$575,"$1,015"
23,Magellan H1st,Per Diem Semi-Private,124,-,"$1,500",$700,NaN,$575,"$1,015"
24,Magellan H1st,Per Diem Semi-Private,124,-,"$1,500",$700,NaN,$575,"$1,015"
25,MagnaCare,Per Diem Semi-Private,124,-,"$1,500",$640,NaN,$575,"$1,015"
26,MCC Commerical,Per Diem Semi-Private,124,-,"$1,500",$830,NaN,$575,"$1,015"
27,Medicare A & B,Per Diem Semi-Private,124,-,"$1,500",$780,NaN,$575,"$1,015"
28,Meritain Health,Per Diem Semi-Private,124,-,"$1,500",$785,NaN,$575,"$1,015"
29,National Association Of Letter Carriers,Per Diem Semi-Private,124,-,"$1,500",$710,NaN,$575,"$1,015"
30,Optum/UMR/GEHA,Per Diem Semi-Private,124,-,"$1,500",$865,NaN,$575,"$1,015"
31,Tricare East,Per Diem Semi-Private,124,-,"$1,500",$700,NaN,$575,"$1,015"
32,United Behavioral Health,Per Diem Semi-Private,124,-,"$1,500",$865,NaN,$575,"$1,015"
33,United Behavioral Health,Per Diem Semi-Private,124,-,"$1,500",$865,NaN,$575,"$1,015"
34,United Behavioral Health,Per Diem Semi-Private,124,-,"$1,500",$865,NaN,$575,"$1,015"
35,United Health Care,Per Diem Semi-Private,124,-,"$1,500",$865,NaN,$575,"$1,015"
36,VA by Optum,Per Diem Semi-Private,124,-,"$1,500",$860,NaN,$575,"$1,015"
37,VA Fee Basis,Per Diem Semi-Private,124,-,"$1,500",$705,NaN,$575,"$1,015"
38,Value Options,Per Diem Semi-Private,124,-,"$1,500",$575,NaN,$575,"$1,015"
39,Wellcare Commercial,Per Diem Semi-Private,124,-,"$1,500",$745,NaN,$575,"$1,015"
40,Wellcare Medicare,Per Diem Semi-Private,124,-,"$1,500",$675,NaN,$575,"$1,015"

In [21]:
columns = df_mid.columns.to_list()
money_columns = columns[4:]
remaining_cols = list(set(columns) - set(money_columns))
df_mid = pd.melt(df_mid, id_vars=remaining_cols)
df_mid['variable'] = df_mid['variable'].replace('rate', 'payer')
df_mid = df_mid.rename(columns={
    'variable': 'rate_category',
    'value': 'standard_charge',
})
df_mid['payer_name'] = df_mid.apply(lambda row: row['payer_name'] if row['rate_category'] == 'Negotiated Rate' else row['rate_category'], 
                                    axis=1)

df_mid

,rev_code,description,payer_name,ndc,rate_category,standard_charge
0,124,Per Diem Semi-Private,Gross Charge,-,Gross Charge,"$1,500"
1,124,Per Diem Semi-Private,Gross Charge,-,Gross Charge,"$1,500"
2,124,Per Diem Semi-Private,Gross Charge,-,Gross Charge,"$1,500"
3,124,Per Diem Semi-Private,Gross Charge,-,Gross Charge,"$1,500"
4,124,Per Diem Semi-Private,Gross Charge,-,Gross Charge,"$1,500"
...,...,...,...,...,...,...
200,124,Per Diem Semi-Private,De-Identified Highest,-,De-Identified Highest,"$1,015"
201,124,Per Diem Semi-Private,De-Identified Highest,-,De-Identified Highest,"$1,015"
202,124,Per Diem Semi-Private,De-Identified Highest,-,De-Identified Highest,"$1,015"
203,124,Per Diem Semi-Private,De-Identified Highest,-,De-Identified Highest,"$1,015"
204,124,Per Diem Semi-Private,De-Identified Highest,-,De-Identified Highest,"$1,015"

In [22]:
set(df_mid['rate_category'].to_list())

{'De-Identified Highest',
 'De-Identified Lowest',
 'Discounted Cash Rate',
 'Gross Charge',
 'Negotiated Rate'}

In [23]:
df_mid.loc[df_mid['rate_category'] == 'De-Identified Highest', 'rate_category'] = 'max'
df_mid.loc[df_mid['rate_category'] == 'De-Identified Lowest', 'rate_category'] = 'min'
df_mid.loc[df_mid['rate_category'] == 'Discounted Cash Rate', 'rate_category'] = 'cash'
df_mid.loc[df_mid['rate_category'] == 'Gross Charge', 'rate_category'] = 'gross'
df_mid.loc[df_mid['rate_category'] == 'Negotiated Rate', 'rate_category'] = 'negotiated'

df_mid['standard_charge'] = df_mid['standard_charge'].astype(str)
df_mid['standard_charge'] = df_mid['standard_charge'].apply(lambda rate: rate.replace("$", "").replace(",", ""))
df_mid['ndc'] = None
df_mid['rev_code'] = df_mid['rev_code'].astype(str)
df_mid['rev_code'] = df_mid['rev_code'].apply(lambda rev_code: "0" + rev_code)
df_mid

,rev_code,description,payer_name,ndc,rate_category,standard_charge
0,0124,Per Diem Semi-Private,Gross Charge,None,gross,1500
1,0124,Per Diem Semi-Private,Gross Charge,None,gross,1500
2,0124,Per Diem Semi-Private,Gross Charge,None,gross,1500
3,0124,Per Diem Semi-Private,Gross Charge,None,gross,1500
4,0124,Per Diem Semi-Private,Gross Charge,None,gross,1500
...,...,...,...,...,...,...
200,0124,Per Diem Semi-Private,De-Identified Highest,None,max,1015
201,0124,Per Diem Semi-Private,De-Identified Highest,None,max,1015
202,0124,Per Diem Semi-Private,De-Identified Highest,None,max,1015
203,0124,Per Diem Semi-Private,De-Identified Highest,None,max,1015
204,0124,Per Diem Semi-Private,De-Identified Highest,None,max,1015

In [24]:
df_mid['hospital_id'] = ccn

df_mid['line_type'] = None
df_mid['ms_drg'] = None
df_mid['apr_drg'] = None
df_mid['eapg'] = None
df_mid['hcpcs_cpt'] = None
df_mid['alt_hcpcs_cpt'] = None
df_mid['thru'] = None
df_mid['apc'] = None
df_mid['icd'] = None
df_mid['drug_hcpcs_multiplier'] = None
df_mid['drug_unit_of_measurement'] = None
df_mid['drug_type_of_measurement'] = None
df_mid['standard_charge_percent'] = None
df_mid['contracting_method'] = None
df_mid['additional_generic_notes'] = None
df_mid['additional_payer_specific_notes'] = None
df_mid['drug_quantity'] = None
df_mid['plan_name'] = None
df_mid['billing_class'] = None
df_mid['setting'] = None
df_mid['local_code'] = None
df_mid['code'] = df_mid['rev_code']
df_mid['modifiers'] = None

df_mid

,rev_code,description,payer_name,ndc,rate_category,standard_charge,hospital_id,line_type,ms_drg,apr_drg,...,contracting_method,additional_generic_notes,additional_payer_specific_notes,drug_quantity,plan_name,billing_class,setting,local_code,code,modifiers
0,0124,Per Diem Semi-Private,Gross Charge,None,gross,1500,104024,None,None,None,...,None,None,None,None,None,None,None,None,0124,None
1,0124,Per Diem Semi-Private,Gross Charge,None,gross,1500,104024,None,None,None,...,None,None,None,None,None,None,None,None,0124,None
2,0124,Per Diem Semi-Private,Gross Charge,None,gross,1500,104024,None,None,None,...,None,None,None,None,None,None,None,None,0124,None
3,0124,Per Diem Semi-Private,Gross Charge,None,gross,1500,104024,None,None,None,...,None,None,None,None,None,None,None,None,0124,None
4,0124,Per Diem Semi-Private,Gross Charge,None,gross,1500,104024,None,None,None,...,None,None,None,None,None,None,None,None,0124,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,0124,Per Diem Semi-Private,De-Identified Highest,None,max,1015,104024,None,None,None,...,None,None,None,None,None,None,None,None,0124,None
201,0124,Per Diem Semi-Private,De-Identified Highest,None,max,1015,104024,None,None,None,...,None,None,None,None,None,None,None,None,0124,None
202,0124,Per Diem Semi-Private,De-Identified Highest,None,max,1015,104024,None,None,None,...,None,None,None,None,None,None,None,None,0124,None
203,0124,Per Diem Semi-Private,De-Identified Highest,None,max,1015,104024,None,None,None,...,None,None,None,None,None,None,None,None,0124,None
204,0124,Per Diem Semi-Private,De-Identified Highest,None,max,1015,104024,None,None,None,...,None,None,None,None,None,None,None,None,0124,None

In [25]:
df_mid = df_mid.dropna(subset=['standard_charge'])
df_mid = df_mid[df_mid['standard_charge'] != 'nan']
df_mid

,rev_code,description,payer_name,ndc,rate_category,standard_charge,hospital_id,line_type,ms_drg,apr_drg,...,contracting_method,additional_generic_notes,additional_payer_specific_notes,drug_quantity,plan_name,billing_class,setting,local_code,code,modifiers
0,0124,Per Diem Semi-Private,Gross Charge,None,gross,1500,104024,None,None,None,...,None,None,None,None,None,None,None,None,0124,None
1,0124,Per Diem Semi-Private,Gross Charge,None,gross,1500,104024,None,None,None,...,None,None,None,None,None,None,None,None,0124,None
2,0124,Per Diem Semi-Private,Gross Charge,None,gross,1500,104024,None,None,None,...,None,None,None,None,None,None,None,None,0124,None
3,0124,Per Diem Semi-Private,Gross Charge,None,gross,1500,104024,None,None,None,...,None,None,None,None,None,None,None,None,0124,None
4,0124,Per Diem Semi-Private,Gross Charge,None,gross,1500,104024,None,None,None,...,None,None,None,None,None,None,None,None,0124,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,0124,Per Diem Semi-Private,De-Identified Highest,None,max,1015,104024,None,None,None,...,None,None,None,None,None,None,None,None,0124,None
201,0124,Per Diem Semi-Private,De-Identified Highest,None,max,1015,104024,None,None,None,...,None,None,None,None,None,None,None,None,0124,None
202,0124,Per Diem Semi-Private,De-Identified Highest,None,max,1015,104024,None,None,None,...,None,None,None,None,None,None,None,None,0124,None
203,0124,Per Diem Semi-Private,De-Identified Highest,None,max,1015,104024,None,None,None,...,None,None,None,None,None,None,None,None,0124,None
204,0124,Per Diem Semi-Private,De-Identified Highest,None,max,1015,104024,None,None,None,...,None,None,None,None,None,None,None,None,0124,None

In [26]:
in_f = open(filename, "r")
date_line = in_f.read().split("\n")[1]
in_f.close()
date_line

'Prices Effective 01/01/2021,,,,,,,,'

In [27]:
df_out = pd.DataFrame(df_mid[TARGET_COLUMNS])
df_out

,hospital_id,line_type,description,rev_code,local_code,code,ms_drg,apr_drg,eapg,hcpcs_cpt,...,billing_class,setting,rate_category,payer_name,plan_name,standard_charge,standard_charge_percent,contracting_method,additional_generic_notes,additional_payer_specific_notes
0,104024,None,Per Diem Semi-Private,0124,None,0124,None,None,None,None,...,None,None,gross,Gross Charge,None,1500,None,None,None,None
1,104024,None,Per Diem Semi-Private,0124,None,0124,None,None,None,None,...,None,None,gross,Gross Charge,None,1500,None,None,None,None
2,104024,None,Per Diem Semi-Private,0124,None,0124,None,None,None,None,...,None,None,gross,Gross Charge,None,1500,None,None,None,None
3,104024,None,Per Diem Semi-Private,0124,None,0124,None,None,None,None,...,None,None,gross,Gross Charge,None,1500,None,None,None,None
4,104024,None,Per Diem Semi-Private,0124,None,0124,None,None,None,None,...,None,None,gross,Gross Charge,None,1500,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,104024,None,Per Diem Semi-Private,0124,None,0124,None,None,None,None,...,None,None,max,De-Identified Highest,None,1015,None,None,None,None
201,104024,None,Per Diem Semi-Private,0124,None,0124,None,None,None,None,...,None,None,max,De-Identified Highest,None,1015,None,None,None,None
202,104024,None,Per Diem Semi-Private,0124,None,0124,None,None,None,None,...,None,None,max,De-Identified Highest,None,1015,None,None,None,None
203,104024,None,Per Diem Semi-Private,0124,None,0124,None,None,None,None,...,None,None,max,De-Identified Highest,None,1015,None,None,None,None
204,104024,None,Per Diem Semi-Private,0124,None,0124,None,None,None,None,...,None,None,max,De-Identified Highest,None,1015,None,None,None,None

In [28]:
df_out.to_csv('104024.csv', index=False)